version: "3"
services:
  camera-app:
    image: gorillagorilla/pi-camera:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
    ports:
      - "3050:3050"
    networks:
      - camnet
    networks:
      - camnet
networks:
  camnet:
